n_epochs: 1000
iter_per_checkpoint: 10000
epoch_per_val: 50
# epoch_per_val: 12
epoch_per_checkpoint: 100
optimiser:  # For Adam optimiser
  lr: 4.e-4
  weight_decay: 1.e-5
scheduler: # For OneCycle scheduler
  max_lr: 4.e-4
  div_factor: 4
  final_div_factor: 10
  steps_per_epoch: 45  # This must be qual to floor(data_len / batch_size)
  # steps_per_epoch: 180  # This must be qual to floor(data_len / batch_size)
  epochs: 1000  # This must be equal to the number of epochs
  pct_start: 0.1
init_state_dict_path:
train_data:  # 11572 (pairs of) samples (wav files)
  clean_noisy_path: configs/valentini_train.txt
  clean_noisy_limit:
  clean_noisy_offset: 0
  sr: 16000
  sub_sample_sec: 1.58125
  target_dB_FS: -27.5
  target_dB_FS_floating_value: 7.5
  dynamic_mixing: True
validation_data:
  clean_noisy_path: configs/valentini_test.txt
  clean_noisy_limit:
  clean_noisy_offset: 0
  sr: 16000
train_dataloader:
  batch_size: 256
  # batch_size: 64
  num_workers: 8
  pin_memory: True
  drop_last: True
  shuffle: True
validation_dataloader:
  batch_size: 1
  num_workers: 0
  pin_memory: False
  drop_last: False
  shuffle: False
auto_mix_precision: False