stft_configs:
  win_len: 400
  hop_len: 100
  fft_len: 512
  win_type: 'hann'
speech_variance_configs:
  encoder_configs:
    encoder_configs:
      - input_dim: 257
        output_dim: 256
        residual_dim: 192
        gate_dim: 192
        skip_dim: 192
        kernel_size: 3
        dilation_list: [1, 2, 4]
        n_stages: 2
        down_sample_factor: 2
        pad_mode: causal
      - input_dim: 128
        output_dim: 64
        residual_dim: 64
        gate_dim: 64
        skip_dim: 64
        kernel_size: 3
        dilation_list: [1, 2, 4]
        n_stages: 2
        down_sample_factor: 2
        pad_mode: causal
    embedding_dims: [128, 64]
    use_batchnorm: False
  decoder_configs:
    decoder_configs:
      - input_dim: 32
        output_dim: 64
        residual_dim: 128
        gate_dim: 128
        skip_dim: 64
        kernel_size: 3
        dilation_list: [1, 2, 4]
        n_stages: 2
        up_sample_factor: 2
        pad_mode: causal
      - input_dim: 128
        output_dim: 257
        residual_dim: 128
        gate_dim: 128
        skip_dim: 256
        kernel_size: 3
        dilation_list: [1, 2, 4]
        n_stages: 4
        up_sample_factor: 2
        pad_mode: causal
        cond_dim: 2
cep_encoder_configs:
  input_dim: 257
  output_dim: 2
  residual_dim: 64
  gate_dim: 64
  skip_dim: 32
  kernel_size: 3
  dilation_list: [1, 2, 4]
  n_stages: 2
  down_sample_factor: 1
  pad_mode: causal
noise_estimator_configs: 
  speech_encoder_configs:
    input_dim: 257
    output_dim: 16
    residual_dim: 64
    gate_dim: 64
    skip_dim: 64
    kernel_size: 3
    dilation_list: [1, 2, 4, 8, 16]
    n_stages: 1
    down_sample_factor: 1
    pad_mode: causal
  noise_decoder_configs:
    input_dim: 257
    output_dim: 257
    residual_dim: 128
    gate_dim: 128
    skip_dim: 128
    kernel_size: 3
    dilation_list: [1, 2, 4]
    n_stages: 4
    up_sample_factor: 1
    pad_mode: causal
    cond_dim: 16
phase_corrector_configs:
  dim: 257
  hidden_dim: 64
  kernel_size: 3
  dilation_list: [1, 2, 4]
  n_stages: 2
  n_rnn_layers: 1
look_ahead_frames: 6
latent_denoising_epochs: 50
noise_estimation_epochs: 50
wiener_type: original
spectral_distribution: exponential